module.exports = [
  "Penut Butter",
  "Tomatoes",
  "Tacos",
  "Hamburger",
  "Cheesebuger",
  "Ceasar Salad",
  "Chop Salad",
  "Baked Potatoe",
  "Quinoa",
  "Beet Soup",
  "Rocky Mountain Oysters",
  "Fish and Chips",
  "Onion Rings",
  "Turkey Diner",
  "Peperoni Pizza",
  "Chocolate Ice Cream",
  "Buttered Toast",
  "Burrito",
  "Pasta with Meatballs",
  "Clam Chowder",
  "Sushi Roll",
  "Orange Sherbert",
  "Birthday Cake",
  "Hot Coffee",
  "Pita and Hummus",
  "Fried Chicken",
  "Grape Jelly",
  "Fruit Salad",
  "Filet Mignon",
  "Fettuccini Alfredo",
  "Carbonara",
  "Lamb Shank",
  "Chicken Noodle Soup",
  "Bagels with Cream Cheese",
  "Hot Dogs",
  "Tamales",
  "Fish Tacos",
  "Yellow Curry",
  "Paella",
  "Casarol",
  "Pot Pie",
  "Snickers",
  "Twix",
  "Reese's",
  "Eggs Benedict",
  "Omelet",
  "Kebabs",
  "Gyro",
  "Tikka Masala",
  "Vindalo",
  "Samosas",
  "Peppercorn Bagel",
  "Pastrami Sandwich",
  "Bacon",
  "Corn on the Cob",
  "Salmon Filet",
  "Halibut and Chips",
  "Grilled Cheese",
  "Flan",
  "Cruch Wrap Supreme",
  "Taco Salad",
  "Deep Dish Pizza",
  "Hot Pocket",
  "Fufu",
  "Corn Bread",
  "Chili",
  "Lima Beans",
  "Stuffing",
  "Echaladas",
  "Carne Asada",
  "Gumbo",
  "Tortallini",
  "French Toast",
  "Waffles",
  "Pancakes",
  "Ramen",
  "Teriaki Chicken",
  "Chipotle Burrito",
  "Double Double",
  "Amimal Fries",
  "Shrimp Salad",
  "Crepes",
  "Cole Slaw",
  "Donuts",
  "Cranberry Juice",
  "Tomatoe Soup",
  "Lobster Bisque",
  "Steamed Crab",
  "Muscles",
  "Clams",
  "Piroski",
  "Shepards Pie",
  "Korean Barbque",
  "Cheese Cake",
  "Fruit Tart",
  "Kim Chi",
  "Quesadilla",
  "Inglourious Basterds",
  "The Kid",
  "Snatch",
  "Monty Python and the Holy Grail",
  "Good Will Hunting",
  "For a Few Dollars More",
  "The Hunt",
  "L.A. Confidential",
  "Scarface",
  "The Apartment",
  "Metropolis",
  "Rashomon",
  "A Separation",
  "Indiana Jones and the Last Crusade",
  "My Father and My Son",
  "Yojimbo",
  "All About Eve",
  "Up",
  "Batman Begins",
  "Some Like It Hot",
  "The Treasure of the Sierra Madre",
  "Unforgiven",
  "Downfall",
  "Die Hard",
  "Raging Bull",
  "Heat",
  "Children of Heaven",
  "The Third Man",
  "The Great Escape",
  "Chinatown",
  "Ikiru",
  "Pan's Labyrinth",
  "My Neighbor Totoro",
  "Ran",
  "The Gold Rush",
  "Inside Out",
  "Incendies",
  "The Secret in Their Eyes",
  "On the Waterfront",
  "Judgment at Nuremberg",
  "The Bridge on the River Kwai",
  "Howl's Moving Castle",
  "Room",
  "Blade Runner",
  "The Seventh Seal",
  "Lock, Stock and Two Smoking Barrels",
  "Mr. Smith Goes to Washington",
  "Casino",
  "A Beautiful Mind",
  "The Elephant Man",
  "Wild Strawberries",
  "V for Vendetta",
  "The Wolf of Wall Street",
  "The General",
  "Warrior",
  "Trainspotting",
  "Dial M for Murder",
  "Andrei Rublev",
  "Gran Torino",
  "Sunrise",
  "Gone with the Wind",
  "The Deer Hunter",
  "The Bandit",
  "Fargo",
  "The Sixth Sense",
  "La La Land",
  "The Thing",
  "The Big Lebowski",
  "No Country for Old Men",
  "Finding Nemo",
  "Tokyo Story",
  "Hacksaw Ridge",
  "Cool Hand Luke",
  "There Will Be Blood",
  "Rebecca",
  "Come and See",
  "Rang De Basanti",
  "The Passion of Joan of Arc",
  "Kill Bill: Vol. 1",
  "How to Train Your Dragon",
  "Logan",
  "Mary and Max",
  "Gone Girl",
  "Into the Wild",
  "Shutter Island",
  "A Wednesday",
  "It Happened One Night",
  "Life of Brian",
  "Wild Tales",
  "Platoon",
  "The Wages of Fear",
  "Hotel Rwanda",
  "Network",
  "Rush",
  "In the Name of the Father",
  "Stand by Me",
  "Persona",
  "The 400 Blows",
  "Ben-Hur",
  "The Grand Budapest Hotel",
  "12 Years a Slave",
  "Mad Max: Fury Road",
  "Memories of Murder",
  "Spotlight",
  "Million Dollar Baby",
  "Jurassic Park",
  "Butch Cassidy and the Sundance Kid",
  "Stalker",
  "Amores Perros",
  "The Truman Show",
  "The Maltese Falcon",
  "Hachi: A Dog's Tale",
  "Nausicaä of the Valley of the Wind",
  "Paper Moon",
  "The Princess Bride",
  "The Nights of Cabiria",
  "Before Sunrise",
  "Munna Bhai M.B.B.S.",
  "Prisoners",
  "Harry Potter and the Deathly Hallows: Part 2",
  "The Grapes of Wrath",
  "Rocky",
  "Catch Me If You Can",
  "Diabolique",
  "Touch of Evil",
  "Gandhi",
  "Star Wars: The Force Awakens",
  "Donnie Darko",
  "Monsters, Inc.",
  "Annie Hall",
  "The Terminator",
  "Barry Lyndon",
  "The Bourne Ultimatum",
  "Sholay",
  "The Wizard of Oz",
  "Groundhog Day",
  "8½",
  "La Haine",
  "Jaws",
  "Twelve Monkeys",
  "The Best Years of Our Lives",
  "Infernal Affairs",
  "Paris, Texas",
  "The Help",
  "In the Mood for Love",
  "Beauty and the Beast",
  "The Battle of Algiers",
  "Dog Day Afternoon",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Gangs of Wasseypur",
  "The Handmaiden",
  "PK",
  "What Ever Happened to Baby Jane?"
];
